from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle,
    KeepTogether
)

from reportlab.lib.styles import (
    getSampleStyleSheet,
    ParagraphStyle
)

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors

from reportlab.lib.enums import (
    TA_CENTER,
    TA_LEFT
)

from reportlab.pdfbase.pdfmetrics import stringWidth

from reportlab.platypus.flowables import Flowable

from reportlab.lib.units import inch

from datetime import datetime

import pandas as pd
import re

import re

def clean_memo_text(text: str) -> str:

    # Remove fenced markdown
    text = re.sub(
        r"```(?:markdown)?",
        "",
        text
    )

    text = text.replace(
        "```",
        ""
    )

    # Remove markdown headers
    text = re.sub(
        r"(?m)^#+\s*",
        "",
        text
    )

    # Remove horizontal rules
    text = re.sub(
        r"(?m)^---+$",
        "",
        text
    )

    # Remove bold markdown
    text = text.replace("**", "")

    # Normalize spacing
    text = re.sub(
        r"\n{3,}",
        "\n\n",
        text
    )

    return text.strip()


# Badge Flowable

class RiskBadge(Flowable):

    def __init__(self, severity):

        Flowable.__init__(self)

        self.severity = severity

        self.width = 80
        self.height = 22

    def draw(self):

        colors_map = {
            "RED": colors.HexColor("#ef4444"),
            "YELLOW": colors.HexColor("#fbbf24"),
            "GREEN": colors.HexColor("#34d399")
        }

        fill = colors_map.get(
            self.severity,
            colors.HexColor("#60a5fa")
        )

        self.canv.setFillColor(fill)

        self.canv.roundRect(
            0,
            0,
            self.width,
            self.height,
            8,
            fill=1,
            stroke=0
        )

        self.canv.setFillColor(colors.black)

        self.canv.setFont(
            "Helvetica-Bold",
            10
        )

        self.canv.drawCentredString(
            self.width / 2,
            7,
            self.severity
        )


# Watermark

def add_watermark(canvas, doc):

    canvas.saveState()

    canvas.setFont(
        "Helvetica",
        9
    )

    canvas.setFillColorRGB(
        0.6,
        0.6,
        0.6
    )

    canvas.drawString(
        40,
        20,
        "Generated by DDGPT"
    )

    canvas.drawRightString(
        560,
        20,
        f"Page {doc.page}"
    )

    canvas.restoreState()


# Styles

def build_styles():

    styles = getSampleStyleSheet()

    styles.add(
        ParagraphStyle(
            name="CoverTitle",
            fontName="Helvetica-Bold",
            fontSize=28,
            leading=34,
            textColor=colors.HexColor("#111827"),
            alignment=TA_CENTER,
            spaceAfter=24
        )
    )

    styles.add(
        ParagraphStyle(
            name="SectionTitle",
            fontName="Helvetica-Bold",
            fontSize=18,
            leading=24,
            textColor=colors.HexColor("#dc2626"),
            spaceBefore=18,
            spaceAfter=14
        )
    )

    styles.add(
        ParagraphStyle(
            name="Body",
            fontName="Helvetica",
            fontSize=11,
            leading=18,
            textColor=colors.HexColor("#1f2937"),
            spaceAfter=10
        )
    )

    styles.add(
        ParagraphStyle(
            name="CustomBullet",
            fontName="Helvetica",
            fontSize=11,
            leading=18,
            leftIndent=18,
            spaceAfter=6
        )
    )

    styles.add(
        ParagraphStyle(
            name="Small",
            fontName="Helvetica",
            fontSize=10,
            leading=14,
            textColor=colors.HexColor("#6b7280")
        )
    )

    return styles


# Clean Text

def clean_text(text: str):

    text = text.replace("**", "")
    text = text.replace("#", "")

    return text.strip()


# Cover Page

def build_cover_page(
    story,
    styles,
    risk_score
):

    story.append(
        Spacer(1, 2 * inch)
    )

    story.append(
        Paragraph(
            "DDGPT",
            styles["CoverTitle"]
        )
    )

    story.append(
        Paragraph(
            "Investment Committee Memorandum",
            styles["SectionTitle"]
        )
    )

    story.append(
        Spacer(1, 0.5 * inch)
    )

    story.append(
        Paragraph(
            f"""
            <b>Generated:</b>
            {datetime.now().strftime("%B %d, %Y")}
            """,
            styles["Body"]
        )
    )

    story.append(
        Paragraph(
            f"""
            <b>Risk Score:</b>
            {risk_score:.2f}
            """,
            styles["Body"]
        )
    )

    story.append(
        Spacer(1, 0.5 * inch)
    )

    story.append(
        Paragraph(
            """
            Confidential institutional diligence report generated
            using DDGPT autonomous diligence workflows.
            """,
            styles["Small"]
        )
    )

    story.append(PageBreak())


# Flags Table

def build_flags_section(
    story,
    styles,
    flags
):

    story.append(
        Paragraph(
            "Risk Findings",
            styles["SectionTitle"]
        )
    )

    for flag in flags:

        story.append(
            RiskBadge(
                flag["severity"]
            )
        )

        story.append(
            Spacer(1, 8)
        )

        story.append(
            Paragraph(
                f"""
                <b>{flag["type"].replace("_", " ")}</b>
                """,
                styles["Body"]
            )
        )

        story.append(
            Paragraph(
                f"""
                <b>Detail:</b>
                {flag["detail"]}
                """,
                styles["Body"]
            )
        )

        story.append(
            Paragraph(
                f"""
                <b>Evidence:</b>
                {flag["evidence"]}
                """,
                styles["Body"]
            )
        )

        story.append(
            Paragraph(
                f"""
                <b>Why It Matters:</b>
                {flag["why_it_matters"]}
                """,
                styles["Body"]
            )
        )

        story.append(
            Paragraph(
                f"""
                <b>Question to Ask:</b>
                {flag["question_to_ask"]}
                """,
                styles["Body"]
            )
        )

        story.append(
            Spacer(1, 18)
        )


# Evidence Table

def build_evidence_table(
    story,
    styles,
    facts_df
):

    story.append(
        Paragraph(
            "Extracted Metrics",
            styles["SectionTitle"]
        )
    )

    table_data = [[
        "Document",
        "Net IRR",
        "Target IRR",
        "TVPI",
        "Mgmt Fee",
        "Carry"
    ]]

    for _, row in facts_df.iterrows():

        table_data.append([
            str(row["doc_name"]),
            str(row["net_irr_pct"]),
            str(row["target_irr_pct"]),
            str(row["tvpi"]),
            str(row["mgmt_fee_pct"]),
            str(row["carry_pct"])
        ])

    table = Table(
        table_data,
        colWidths=[
            2.6 * inch,
            0.9 * inch,
            1.0 * inch,
            0.8 * inch,
            0.9 * inch,
            0.8 * inch
        ]
    )

    table.setStyle(
        TableStyle([

            (
                "BACKGROUND",
                (0, 0),
                (-1, 0),
                colors.HexColor("#111827")
            ),

            (
                "TEXTCOLOR",
                (0, 0),
                (-1, 0),
                colors.white
            ),

            (
                "FONTNAME",
                (0, 0),
                (-1, 0),
                "Helvetica-Bold"
            ),

            (
                "GRID",
                (0, 0),
                (-1, -1),
                0.5,
                colors.HexColor("#d1d5db")
            ),

            (
                "ROWBACKGROUNDS",
                (0, 1),
                (-1, -1),
                [
                    colors.white,
                    colors.HexColor("#f3f4f6")
                ]
            ),

            (
                "BOTTOMPADDING",
                (0, 0),
                (-1, 0),
                10
            ),

            (
                "TOPPADDING",
                (0, 0),
                (-1, -1),
                8
            ),

            (
                "BOTTOMPADDING",
                (0, 1),
                (-1, -1),
                8
            )

        ])
    )

    story.append(table)

    story.append(
        Spacer(1, 24)
    )


# Memo Body

def build_memo_body(
    story,
    styles,
    memo
):

    story.append(
        Paragraph(
            "Full IC Memorandum",
            styles["SectionTitle"]
        )
    )

    lines = memo.split("\n")

    for line in lines:

        line = line.strip()

        if not line:

            story.append(
                Spacer(1, 8)
            )

            continue

        clean = clean_text(line)

        if clean.lower().startswith(
            (
                "top",
                "inconsistencies",
                "recommendation",
                "questions"
            )
        ):

            story.append(
                Paragraph(
                    clean,
                    styles["SectionTitle"]
                )
            )

            continue

        if line.startswith("-") or re.match(
            r"^\d+\.",
            line
        ):

            story.append(
                Paragraph(
                    clean,
                    styles["CustomBullet"]
                )
            )

            continue

        story.append(
            Paragraph(
                clean,
                styles["Body"]
            )
        )


# Main Render

def render_ic_pdf(
    output_path: str,
    memo: str,
    flags,
    facts_df,
    risk_score
):
    memo = clean_memo_text(memo)

    styles = build_styles()

    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        rightMargin=48,
        leftMargin=48,
        topMargin=48,
        bottomMargin=48
    )

    story = []

    build_cover_page(
        story,
        styles,
        risk_score
    )

    build_flags_section(
        story,
        styles,
        flags
    )

    build_evidence_table(
        story,
        styles,
        facts_df
    )

    build_memo_body(
        story,
        styles,
        memo
    )

    doc.build(
        story,
        onFirstPage=add_watermark,
        onLaterPages=add_watermark
    )